apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis-namespace
spec:
  releaseName: redis
  chart:
    spec:
      chart: helm_charts/redis
      version: 17.10.2
      sourceRef:
        kind: GitRepository
        name: fluxcd-helm-test
        namespace: flux-system
  interval: 5m
  values:
    architecture: standalone
    persistence:
      enabled: false
    replica:
      replicaCount: 1
    service:
      type: ClusterIP
    securityContext:
      enabled: false
